# Generated by Django 5.2.7 on 2025-10-24 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('group_type', models.CharField(choices=[('Independent', 'Independent'), ('Dependent', 'Dependent')], default='Independent', max_length=20)),
                ('group_option', models.CharField(choices=[('optional', 'Optional'), ('required', 'Required'), ('multiple', 'Can be selected more than once')], default='optional', max_length=20)),
                ('min_pref', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('max_pref', models.PositiveIntegerField(blank=True, default=10, null=True)),
                ('pricing_method', models.CharField(choices=[('No Charge', 'No Charge'), ('Group Pricing', 'Group Pricing'), ('Individual Pricing', 'Individual Pricing')], default='No Charge', max_length=30)),
                ('group_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='restaurantApp.preferencegroup')),
            ],
        ),
        migrations.CreateModel(
            name='DependentIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='restaurantApp.preferencegroup')),
            ],
        ),
        migrations.CreateModel(
            name='DependentColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='restaurantApp.preferencegroup')),
            ],
        ),
        migrations.CreateModel(
            name='DependentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=False)),
                ('default', models.BooleanField(default=False)),
                ('required', models.BooleanField(default=False)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='restaurantApp.dependentcolumn')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='restaurantApp.dependentingredient')),
            ],
            options={
                'unique_together': {('ingredient', 'column')},
            },
        ),
    ]
