# Generated by Django 5.2.7 on 2025-10-29 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('group_type', models.CharField(choices=[('Independent', 'Independent'), ('Dependent', 'Dependent')], default='Independent', max_length=20)),
                ('group_option', models.CharField(choices=[('optional', 'Optional'), ('required', 'Required'), ('multiple', 'Can be selected more than once')], default='optional', max_length=20)),
                ('min_pref', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('max_pref', models.PositiveIntegerField(blank=True, default=10, null=True)),
                ('pricing_method', models.CharField(choices=[('No Charge', 'No Charge'), ('Group Pricing', 'Group Pricing'), ('Individual Pricing', 'Individual Pricing')], default='No Charge', max_length=30)),
                ('group_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreferenceGroupDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_type', models.CharField(choices=[('preference', 'Preference'), ('ingredient', 'Ingredient'), ('column', 'Column'), ('rule', 'Rule')], max_length=20)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('show', models.BooleanField(blank=True, default=False, null=True)),
                ('default', models.BooleanField(blank=True, default=False, null=True)),
                ('required', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='restaurantApp.preferencegroup')),
                ('parent_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_rules', to='restaurantApp.preferencegroupdetail')),
                ('related_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='restaurantApp.preferencegroupdetail')),
            ],
            options={
                'indexes': [models.Index(fields=['group', 'detail_type'], name='restaurantA_group_i_a5676c_idx'), models.Index(fields=['parent_detail', 'related_detail'], name='restaurantA_parent__90ab14_idx')],
            },
        ),
    ]
