# Generated by Django 5.2.7 on 2025-10-29 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DependentColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='restaurantApp.preferencegroup')),
            ],
        ),
        migrations.CreateModel(
            name='DependentIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='restaurantApp.preferencegroup')),
            ],
        ),
        migrations.CreateModel(
            name='DependentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=False)),
                ('default', models.BooleanField(default=False)),
                ('required', models.BooleanField(default=False)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='restaurantApp.dependentcolumn')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='restaurantApp.dependentingredient')),
            ],
            options={
                'unique_together': {('ingredient', 'column')},
            },
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='restaurantApp.preferencegroup')),
            ],
        ),
        migrations.DeleteModel(
            name='PreferenceGroupDetail',
        ),
    ]
