# Generated by Django 5.2.7 on 2025-10-31 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0002_dependentcolumn_dependentingredient_dependentrule_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dependentcolumn',
            options={'ordering': ['order_index']},
        ),
        migrations.AlterModelOptions(
            name='dependentingredient',
            options={'ordering': ['order_index']},
        ),
        migrations.AlterModelOptions(
            name='preference',
            options={'ordering': ['order_index']},
        ),
        migrations.AddField(
            model_name='dependentcolumn',
            name='order_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dependentingredient',
            name='order_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='preference',
            name='order_index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
