# Generated by Django 5.2.7 on 2025-11-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0003_alter_dependentcolumn_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferencegroup',
            name='multiple_selection_limit',
            field=models.BooleanField(default=False),
        ),
    ]
