# Generated by Django 5.2.7 on 2025-11-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0004_preferencegroup_multiple_selection_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferencegroup',
            name='child_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='preferencegroup',
            name='parent_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
