# Generated by Django 5.2.7 on 2025-11-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0005_preferencegroup_child_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferencegroup',
            name='child_name',
            field=models.CharField(default='Add Row', max_length=100),
        ),
        migrations.AlterField(
            model_name='preferencegroup',
            name='parent_name',
            field=models.CharField(default='Add Column', max_length=100),
        ),
    ]
