# Generated by Django 5.2.7 on 2025-11-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0006_alter_preferencegroup_child_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependentrule',
            name='allow_more',
            field=models.BooleanField(default=False),
        ),
    ]
