# Generated by Django 5.2.7 on 2025-11-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0007_dependentrule_allow_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferencegroup',
            name='group_option',
            field=models.CharField(choices=[('optional', 'Optional'), ('required', 'Required'), ('multiple', 'Can be selected more than once'), ('N/A', 'N/A')], default='optional', max_length=20),
        ),
    ]
